"""
For each new job, call the Claude API to draft a tailored cover letter
and a CV adapted to that specific role, using data/base_cv.md as background context.

Requires: ANTHROPIC_API_KEY environment variable.
"""

import os
import json
from pathlib import Path
from datetime import date
import anthropic

DATA_DIR = Path(__file__).parent.parent / "data"
DOCS_DIR = Path(__file__).parent.parent / "docs"

client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

# Fixed personal/contact details — never regenerated by the model, so they can
# never drift from what's on file. Sourced from Maria's real CV template.
CV_NAME = "Maria Silva"
CV_CONTACT = (
    "38, Marlborough Road, Maidenhead, Berkshire · +447935308070 · "
    "mariafgsilva10@gmail.com · linkedin.com/in/mariafgsilva10"
)

SYSTEM_PROMPT = """You are drafting job application materials for Maria Silva, \
a UK-based aspiring paralegal. Her cover-letter voice and drafting rules below are \
the most important instructions here — follow them exactly, not generic norms for \
"a good cover letter".

VOICE: direct and confident without exaggerating. Personal, not generic. Clear and \
fairly simple, not academic or overly formal. Specific about what she actually did, \
learned or found interesting. Reflective where it explains motivation or career \
development. Evidence-based, never relying on unsupported claims about her \
abilities. The result should read like something an intelligent applicant wrote \
carefully herself — not like an AI-generated candidate.

DO NOT DO ANY OF THE FOLLOWING — these are the specific tells of AI-generated \
application writing and must not appear:
- Unnecessary dashes; excessive colons or overly structured rhetorical devices
- "Together, these experiences…"-style summarising transitions
- "It is not only X, but also Y" where a simpler sentence would do
- Repetitive three-part lists used purely for rhetorical effect
- Clichés: "I am particularly drawn to…", "This opportunity strongly aligns \
with…", "I would relish the opportunity…", "I am excited by the prospect of…", \
or similar corporate stock phrases
- Calling something a "profound impact" or her "greatest influence" when it \
simply developed or sparked an interest
- Saying an experience "reinforced my passion" — say specifically what changed \
in her understanding or interests instead
- Overusing: particularly, further, unique, dynamic, prestigious, renowned, \
multifaceted, intersection, navigate, landscape, seamlessly
- Needlessly sophisticated wording — natural, simple wording beats \
impressive-sounding wording

ANSWER FIRST: open the letter by directly stating the role, why it genuinely \
interests her, and why her background is relevant. Never open with an empty \
paragraph that only says she is writing to apply.

BUILD THE LETTER AROUND THE JOB DESCRIPTION, NOT A GENERIC CV SUMMARY: identify \
the role's main responsibilities and the skills or competencies the ad repeatedly \
emphasises, then choose the 2-3 strongest pieces of evidence from her background \
for those specific requirements — depth over listing everything she has done. Use \
the job ad's own wording naturally where it's accurate to do so (e.g. case \
management, document review, legal research, client communication, drafting, \
file/deadline management, stakeholder communication, data handling, attention to \
detail) but never just copy it — show evidence of having done comparable work. \
Explicitly draw the connection for the reader rather than leaving them to infer \
it: not "I developed strong organisational skills at BCLP" but something like \
"At BCLP I tracked deadlines and coordinated work across an international \
arbitration matter, which required the organisation relevant to managing case \
files in this role."

EVIDENCE BEFORE ADJECTIVES: never simply assert she is organised, analytical, \
resilient, commercially aware, a strong communicator, detail-oriented or \
proactive. Show something she did that demonstrates it. Preferred shape: \
experience -> what she actually did -> concrete evidence or outcome -> the skill \
it demonstrates -> why that's relevant to this role's responsibilities.

STRUCTURE: Opening (role, genuine reason for interest, why her background fits) \
-> Relevant Experience (2-3 strongest examples in real depth) -> Why This Role \
(specific reasoning connecting the role to her experience and developing \
interests — never just complimenting the employer in the abstract) -> a short \
conclusion that does not repeat what's already been said. Keep it under 400 \
words and cut anything that doesn't directly serve the argument — no generic \
praise of the employer, no long introduction, no elaborate closing.

BE ACCURATE, DON'T INFLATE: describe what an experience actually did for her — \
sparked an interest, developed it, clarified something, exposed her to something \
new — rather than reaching for a more dramatic claim than is true.

SELF-EDIT BEFORE FINISHING: cut overly symmetrical sentences, repeated sentence \
structures, rhetorical lists, corporate clichés, abstract nouns, excessive \
adjectives, artificial transitions, exaggerated enthusiasm, and any sentence \
that sounds impressive but says nothing concrete. It should stay professional, \
not casual — but read like a real person with a clear, specific reason for \
applying. If another applicant could copy a paragraph unchanged, rewrite it to \
be specific to her.

You will be given her full background/base CV and a job description. Produce two \
documents, both ready to send as-is:

1. A tailored cover letter, following every rule above, under 400 words.
2. Her CV adapted specifically for this role: reorder entries and bullets so the most \
relevant experience leads, tighten and re-word bullets to mirror the job ad's own \
language where it's accurate to do so, and trim or de-emphasise less relevant detail. \
Never invent experience, qualifications, dates, employers, or achievements that aren't \
in her background — only reorder, re-word, and re-emphasise what's true.

Do NOT include her name or contact details in the CV — those are added separately. \
Structure the adapted CV as JSON matching exactly this shape:

{
  "summary": "one paragraph, adapted to lead with what's most relevant to this role",
  "education": [
    {"title": "degree name + classification", "institution": "institution name",
     "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "experience": [
    {"employer": "employer name", "location": "city", "role": "job title \
(add ' — <rotation/team>' after the role if a placement had distinct rotations \
worth listing as separate entries)", "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "skills": [
    {"label": "Languages", "text": "..."},
    {"label": "Technical skills", "text": "..."},
    {"label": "Case and evidence management", "text": "..."}
  ]
}

Keep the same education/experience/skills entries as the background CV (reordered and \
re-emphasised, not cut) unless something is clearly irrelevant enough to drop. Bullets \
should stay close to their original length — tightened and re-worded, not padded.

Always produce both documents using whatever information you're given, even if the job \
description is partial, truncated, or thin — including when the role is a poor or \
unrelated match for a legal/paralegal background. Never ask a question, request more \
detail, comment on the job's suitability, or write anything other than the two \
documents — do your best with what's provided.

Output valid JSON only, with top-level keys "cover_letter" (string) and "adapted_cv" \
(the object shape above). Your entire response must be nothing but that JSON object: \
no markdown fences, no preamble, no commentary or notes before or after it. The very \
first character of your response must be "{" and the very last character must be "}"."""


def draft_for_job(job, base_cv_text):
    user_prompt = f"""BACKGROUND (Maria's full base CV):
{base_cv_text}

JOB TITLE: {job['title']}
EMPLOYER: {job['employer']}
LOCATION: {job['location']}
JOB DESCRIPTION:
{job['description'][:4000]}
"""

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4500,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )
    text = resp.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        # Defense in depth: if the model added any stray commentary before/after
        # the JSON despite being told not to, try to recover just the JSON object
        # rather than falling back to dumping raw text as the "cover letter".
        start, end = text.find("{"), text.rfind("}")
        result = None
        if start != -1 and end != -1 and end > start:
            try:
                result = json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                result = None
        if result is None:
            result = {"cover_letter": text, "adapted_cv": None}

    # Name/contact are fixed and never model-generated — attach them here so
    # data.json always carries a complete, renderable CV object.
    if isinstance(result.get("adapted_cv"), dict):
        result["adapted_cv"]["name"] = CV_NAME
        result["adapted_cv"]["contact"] = CV_CONTACT

    return result


def main():
    new_jobs_file = DATA_DIR / "new_jobs.json"
    if not new_jobs_file.exists():
        print("No new_jobs.json found, nothing to draft")
        return

    new_jobs = json.loads(new_jobs_file.read_text())
    base_cv_text = (DATA_DIR / "base_cv.md").read_text()

    drafted = []
    for job in new_jobs:
        print(f"Drafting for: {job['title']} @ {job['employer']}")
        try:
            draft = draft_for_job(job, base_cv_text)
        except Exception as e:
            print(f"  Failed: {e}")
            draft = {"cover_letter": f"(drafting failed: {e})", "adapted_cv": None}
        drafted.append({**job, **draft})

    # Load existing dashboard history, prepend today's batch
    dashboard_file = DOCS_DIR / "data.json"
    history = []
    if dashboard_file.exists():
        history = json.loads(dashboard_file.read_text())

    today_entry = {"date": str(date.today()), "jobs": drafted}
    history.insert(0, today_entry)
    history = history[:30]  # keep last 30 days

    DOCS_DIR.mkdir(exist_ok=True)
    dashboard_file.write_text(json.dumps(history, indent=2))
    print(f"Wrote {len(drafted)} drafted jobs to dashboard")


if __name__ == "__main__":
    main()
