"""
For each new job, call the Claude API to draft a tailored cover letter
and a CV adapted to that specific role, using data/base_cv.md as background context.

Requires: ANTHROPIC_API_KEY environment variable.
"""

import os
import json
from pathlib import Path
from datetime import date
import anthropic

DATA_DIR = Path(__file__).parent.parent / "data"
DOCS_DIR = Path(__file__).parent.parent / "docs"

client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

# Fixed personal/contact details — never regenerated by the model, so they can
# never drift from what's on file. Sourced from Maria's real CV template.
CV_NAME = "Maria Silva"
CV_CONTACT = (
    "38, Marlborough Road, Maidenhead, Berkshire · +447935308070 · "
    "mariafgsilva10@gmail.com · linkedin.com/in/mariafgsilva10"
)

SYSTEM_PROMPT = """You are drafting job application materials for Maria Silva, \
a UK-based aspiring paralegal. Follow her stated writing preferences exactly:

- Purpose-led opening, no fluff, no academic framing, no absolutist language
- Concise, clear, structured, polished but natural
- Mirror the employer's own wording where the job ad gives you language to mirror
- Emphasise: disputes experience, commercial awareness, client-focused judgement, \
attention to detail, drafting/research and litigation-adjacent capability
- Cover letters should be under 400 words, no generic filler paragraphs

You will be given her full background/base CV and a job description. Produce two \
documents, both ready to send as-is:

1. A tailored cover letter (under 400 words, no generic filler).
2. Her CV adapted specifically for this role: reorder entries and bullets so the most \
relevant experience leads, tighten and re-word bullets to mirror the job ad's own \
language where it's accurate to do so, and trim or de-emphasise less relevant detail. \
Never invent experience, qualifications, dates, employers, or achievements that aren't \
in her background — only reorder, re-word, and re-emphasise what's true.

Do NOT include her name or contact details in the CV — those are added separately. \
Structure the adapted CV as JSON matching exactly this shape:

{
  "summary": "one paragraph, adapted to lead with what's most relevant to this role",
  "education": [
    {"title": "degree name + classification", "institution": "institution name",
     "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "experience": [
    {"employer": "employer name", "location": "city", "role": "job title \
(add ' — <rotation/team>' after the role if a placement had distinct rotations \
worth listing as separate entries)", "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "skills": [
    {"label": "Languages", "text": "..."},
    {"label": "Technical skills", "text": "..."},
    {"label": "Case and evidence management", "text": "..."}
  ]
}

Keep the same education/experience/skills entries as the background CV (reordered and \
re-emphasised, not cut) unless something is clearly irrelevant enough to drop. Bullets \
should stay close to their original length — tightened and re-worded, not padded.

Always produce both documents using whatever information you're given, even if the job \
description is partial, truncated, or thin — including when the role is a poor or \
unrelated match for a legal/paralegal background. Never ask a question, request more \
detail, comment on the job's suitability, or write anything other than the two \
documents — do your best with what's provided.

Output valid JSON only, with top-level keys "cover_letter" (string) and "adapted_cv" \
(the object shape above). Your entire response must be nothing but that JSON object: \
no markdown fences, no preamble, no commentary or notes before or after it. The very \
first character of your response must be "{" and the very last character must be "}"."""


def draft_for_job(job, base_cv_text):
    user_prompt = f"""BACKGROUND (Maria's full base CV):
{base_cv_text}

JOB TITLE: {job['title']}
EMPLOYER: {job['employer']}
LOCATION: {job['location']}
JOB DESCRIPTION:
{job['description'][:4000]}
"""

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4500,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )
    text = resp.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        # Defense in depth: if the model added any stray commentary before/after
        # the JSON despite being told not to, try to recover just the JSON object
        # rather than falling back to dumping raw text as the "cover letter".
        start, end = text.find("{"), text.rfind("}")
        result = None
        if start != -1 and end != -1 and end > start:
            try:
                result = json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                result = None
        if result is None:
            result = {"cover_letter": text, "adapted_cv": None}

    # Name/contact are fixed and never model-generated — attach them here so
    # data.json always carries a complete, renderable CV object.
    if isinstance(result.get("adapted_cv"), dict):
        result["adapted_cv"]["name"] = CV_NAME
        result["adapted_cv"]["contact"] = CV_CONTACT

    return result


def main():
    new_jobs_file = DATA_DIR / "new_jobs.json"
    if not new_jobs_file.exists():
        print("No new_jobs.json found, nothing to draft")
        return

    new_jobs = json.loads(new_jobs_file.read_text())
    base_cv_text = (DATA_DIR / "base_cv.md").read_text()

    drafted = []
    for job in new_jobs:
        print(f"Drafting for: {job['title']} @ {job['employer']}")
        try:
            draft = draft_for_job(job, base_cv_text)
        except Exception as e:
            print(f"  Failed: {e}")
            draft = {"cover_letter": f"(drafting failed: {e})", "adapted_cv": None}
        drafted.append({**job, **draft})

    # Load existing dashboard history, prepend today's batch
    dashboard_file = DOCS_DIR / "data.json"
    history = []
    if dashboard_file.exists():
        history = json.loads(dashboard_file.read_text())

    today_entry = {"date": str(date.today()), "jobs": drafted}
    history.insert(0, today_entry)
    history = history[:30]  # keep last 30 days

    DOCS_DIR.mkdir(exist_ok=True)
    dashboard_file.write_text(json.dumps(history, indent=2))
    print(f"Wrote {len(drafted)} drafted jobs to dashboard")


if __name__ == "__main__":
    main()
