"""
Put each day's new jobs on the dashboard, and - only when asked - draft a
tailored cover letter and adapted CV for a specific job.

DRAFTING IS OPT-IN. The daily run used to draft for every new job, which meant
paying for roughly ten cover letters and ten CV rewrites a day when Maria
actually applies to a handful. So the default mode here just merges the new
jobs into docs/data.json and makes no API call at all; the daily run costs
nothing to draft.

Two ways to draft, both on demand:

  python scripts/draft_materials.py --draft <job-id> [<job-id> ...]
  python scripts/draft_materials.py --draft all

    Uses the Claude API and needs ANTHROPIC_API_KEY. Writes the results back
    into docs/data.json, so generate_pdfs.py can then render the PDFs.

  The "Write CV & cover letter" button on the dashboard

    Opens the Claude desktop app with the job's details and asks Claude to do
    the same job against SYSTEM_PROMPT below. That route uses Maria's Claude
    subscription rather than API credit, so it costs nothing extra per letter.
    It is the route the dashboard points at.

Either way the output shape is identical: a "cover_letter" string and an
"adapted_cv" object on the job in docs/data.json.
"""

import argparse
import os
import json
from pathlib import Path
from datetime import date

DATA_DIR = Path(__file__).parent.parent / "data"
DOCS_DIR = Path(__file__).parent.parent / "docs"

# Fixed personal/contact details — never regenerated by the model, so they can
# never drift from what's on file. Sourced from Maria's real CV template.
CV_NAME = "Maria Silva"
CV_CONTACT = (
    "38, Marlborough Road, Maidenhead, Berkshire · +447935308070 · "
    "mariafgsilva10@gmail.com · linkedin.com/in/mariafgsilva10"
)

SYSTEM_PROMPT = """You are drafting job application materials for Maria Silva, \
a UK-based aspiring paralegal. Her cover-letter voice and drafting rules below are \
the most important instructions here — follow them exactly, not generic norms for \
"a good cover letter".

VOICE: direct and confident without exaggerating. Personal, not generic. Clear and \
fairly simple, not academic or overly formal. Specific about what she actually did, \
learned or found interesting. Reflective where it explains motivation or career \
development. Evidence-based, never relying on unsupported claims about her \
abilities. The result should read like something an intelligent applicant wrote \
carefully herself — not like an AI-generated candidate.

HARD RULE — NO DASHES: never use an em dash or en dash anywhere in the cover \
letter, for any reason (not for asides, not for joining clauses, not for a range). \
This is a strict ban, not a style preference. If you would reach for a dash, \
rewrite as two separate sentences, or use a comma or parentheses instead. Ordinary \
hyphens inside compound words (client-focused, detail-oriented) are fine — it is \
only the sentence-punctuation dash that is banned.

HARD RULE — NO COLONS: never use a colon anywhere in the letter, for any \
reason. Maria reads colons as a giveaway of AI-generated writing. Rephrase as \
separate sentences instead.

HARD RULE — NO CONTRACTIONS OR ABBREVIATIONS: always spell words out in full. \
Write "do not" and "it is", never the shortened forms. This applies throughout.

HARD RULE — ONE PAGE MAXIMUM: the letter must fit on a single A4 page. Keep it \
under 350 words. This is a hard ceiling, not a target to write up to.

BANNED CONSTRUCTIONS — these read as AI writing to her and must never appear:
- "my interest comes from X rather than Y", or any contrastive framing used to \
explain where an interest came from. State directly where it came from and why.
- "where X meets Y" (as in "where legal reasoning meets a client's business \
problem"), and any variation of it.

EVERY FACT MUST EARN ITS PLACE: never state a piece of her background as a bare \
fact. Each one has to connect to something the employer's own ad or the \
opportunity's stated criteria actually asks for, and the letter should make that \
connection explicit. Her law degree belongs in a letter because the role calls \
for legal analysis, not because she studied law.

DO NOT DO ANY OF THE FOLLOWING — these are the specific tells of AI-generated \
application writing and must not appear:
- Overly structured rhetorical devices
- "Together, these experiences…"-style summarising transitions
- "It is not only X, but also Y" where a simpler sentence would do
- Repetitive three-part lists used purely for rhetorical effect
- Clichés: "I am particularly drawn to…", "This opportunity strongly aligns \
with…", "I would relish the opportunity…", "I am excited by the prospect of…", \
or similar corporate stock phrases
- Calling something a "profound impact" or her "greatest influence" when it \
simply developed or sparked an interest
- Saying an experience "reinforced my passion" — say specifically what changed \
in her understanding or interests instead
- Overusing: particularly, further, unique, dynamic, prestigious, renowned, \
multifaceted, intersection, navigate, landscape, seamlessly
- Needlessly sophisticated wording — natural, simple wording beats \
impressive-sounding wording

NO SALUTATION OR SIGN-OFF: write only the body paragraphs. Do not include a \
salutation line (e.g. "Dear Hiring Manager,") and do not include a closing or \
signature (e.g. "Yours sincerely, Maria Silva") — those are added automatically \
afterwards, so including them yourself would duplicate them.

ANSWER FIRST: the body's first sentence should directly state the role, why it \
genuinely interests her, and why her background is relevant. Never open with an \
empty paragraph that only says she is writing to apply.

BUILD THE LETTER AROUND THE JOB DESCRIPTION, NOT A GENERIC CV SUMMARY: identify \
the role's main responsibilities and the skills or competencies the ad repeatedly \
emphasises, then choose the 2-3 strongest pieces of evidence from her background \
for those specific requirements — depth over listing everything she has done. Use \
the job ad's own wording naturally where it's accurate to do so (e.g. case \
management, document review, legal research, client communication, drafting, \
file/deadline management, stakeholder communication, data handling, attention to \
detail) but never just copy it — show evidence of having done comparable work. \
Explicitly draw the connection for the reader rather than leaving them to infer \
it: not "I developed strong organisational skills at BCLP" but something like \
"At BCLP I tracked deadlines and coordinated work across an international \
arbitration matter, which required the organisation relevant to managing case \
files in this role."

PERSONALISE THROUGH A NARRATIVE, NOT A CREDENTIALS LIST: where genuinely relevant to \
the role, build her motivation as a chronological progression rather than stating \
interest abstractly: something specific sparked the interest -> she took an independent \
step to develop it -> she sought practical exposure -> this role is the next logical \
step. Never write "I am interested in X because it is dynamic/exciting/fast-paced" - \
point to the specific experience in her background that shows why, using her \
Firm Engagement, Courses & Events material where it fits the role's practice area or \
firm. Only use what's genuinely relevant to this specific role; do not force in \
unrelated events or courses just because they exist, and do not repeat a whole \
progression chain if only one step of it is relevant. Most paralegal/legal-assistant \
roles in this search are general commercial, disputes or conveyancing roles, so her \
BCLP, Citizens Advice and LLM background remain the primary evidence for most \
applications - bring in the private equity/finance narrative (A&O Shearman open day, \
the Coursera course, the Clifford Chance programme) specifically when a role or \
employer relates to private equity, corporate finance or banking.

EVIDENCE BEFORE ADJECTIVES: never simply assert she is organised, analytical, \
resilient, commercially aware, a strong communicator, detail-oriented or \
proactive. Show something she did that demonstrates it. Preferred shape: \
experience -> what she actually did -> concrete evidence or outcome -> the skill \
it demonstrates -> why that's relevant to this role's responsibilities.

STRUCTURE: Opening (role, genuine reason for interest, why her background fits) \
-> Relevant Experience (2-3 strongest examples in real depth) -> Why This Role \
(specific reasoning connecting the role to her experience and developing \
interests — never just complimenting the employer in the abstract) -> a short \
conclusion that does not repeat what's already been said. Keep it under 350 \
words and cut anything that doesn't directly serve the argument — no generic \
praise of the employer, no long introduction, no elaborate closing.

BE ACCURATE, DON'T INFLATE: describe what an experience actually did for her — \
sparked an interest, developed it, clarified something, exposed her to something \
new — rather than reaching for a more dramatic claim than is true.

SELF-EDIT BEFORE FINISHING: cut overly symmetrical sentences, repeated sentence \
structures, rhetorical lists, corporate clichés, abstract nouns, excessive \
adjectives, artificial transitions, exaggerated enthusiasm, and any sentence \
that sounds impressive but says nothing concrete. It should stay professional, \
not casual, but read like a real person with a clear, specific reason for \
applying. If another applicant could copy a paragraph unchanged, rewrite it to \
be specific to her. As a final check, read back through the letter for any em \
dash, en dash, colon, or contraction, and rewrite those sentences without them \
before finishing. Count the words and confirm the total is under 350.

You will be given her full background/base CV and a job description. Produce two \
documents, both ready to send as-is:

1. A tailored cover letter, following every rule above, under 350 words.
2. Her CV adapted specifically for this role: reorder entries and bullets so the most \
relevant experience leads, tighten and re-word bullets to mirror the job ad's own \
language where it's accurate to do so, and trim or de-emphasise less relevant detail. \
Never invent experience, qualifications, dates, employers, or achievements that aren't \
in her background — only reorder, re-word, and re-emphasise what's true.

Do NOT include her name or contact details in the CV — those are added separately. \
Structure the adapted CV as JSON matching exactly this shape:

{
  "summary": "one paragraph, adapted to lead with what's most relevant to this role",
  "education": [
    {"title": "degree name + classification", "institution": "institution name",
     "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "experience": [
    {"employer": "employer name", "location": "city", "role": "job title \
(add ' — <rotation/team>' after the role if a placement had distinct rotations \
worth listing as separate entries)", "dateline": "date range", "bullets": ["...", "..."]}
  ],
  "skills": [
    {"label": "Languages", "text": "..."},
    {"label": "Technical skills", "text": "..."},
    {"label": "Case and evidence management", "text": "..."}
  ]
}

Keep the same education/experience/skills entries as the background CV (reordered and \
re-emphasised, not cut) unless something is clearly irrelevant enough to drop. Bullets \
should stay close to their original length — tightened and re-worded, not padded.

Always produce both documents using whatever information you're given, even if the job \
description is partial, truncated, or thin — including when the role is a poor or \
unrelated match for a legal/paralegal background. Never ask a question, request more \
detail, comment on the job's suitability, or write anything other than the two \
documents — do your best with what's provided.

Output valid JSON only, with top-level keys "cover_letter" (string) and "adapted_cv" \
(the object shape above). Your entire response must be nothing but that JSON object: \
no markdown fences, no preamble, no commentary or notes before or after it. The very \
first character of your response must be "{" and the very last character must be "}"."""


def build_user_prompt(job, base_cv_text):
    return f"""BACKGROUND (Maria's full base CV):
{base_cv_text}

JOB TITLE: {job['title']}
EMPLOYER: {job['employer']}
LOCATION: {job['location']}
JOB DESCRIPTION:
{job['description'][:4000]}
"""


def draft_for_job(job, base_cv_text):
    # Imported here rather than at module scope so the default collect-only
    # run needs neither the anthropic package nor an API key.
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    user_prompt = build_user_prompt(job, base_cv_text)

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4500,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )
    text = resp.content[0].text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    parsed_cleanly = True
    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        # Defense in depth: if the model added any stray commentary before/after
        # the JSON despite being told not to, try to recover just the JSON object
        # rather than falling back to dumping raw text as the "cover letter".
        start, end = text.find("{"), text.rfind("}")
        result = None
        if start != -1 and end != -1 and end > start:
            try:
                result = json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                result = None
        if result is None:
            result = {"cover_letter": text, "adapted_cv": None}
            parsed_cleanly = False

    # Name/contact are fixed and never model-generated — attach them here so
    # data.json always carries a complete, renderable CV object.
    if isinstance(result.get("adapted_cv"), dict):
        result["adapted_cv"]["name"] = CV_NAME
        result["adapted_cv"]["contact"] = CV_CONTACT

    # The salutation and sign-off are fixed and never model-generated, so every
    # letter is consistently formatted and ready to drop straight into a PDF.
    if parsed_cleanly and isinstance(result.get("cover_letter"), str) and result["cover_letter"].strip():
        body = result["cover_letter"].strip()
        result["cover_letter"] = f"Dear Hiring Manager,\n\n{body}\n\nYours sincerely,\nMaria Silva"

    return result


def load_history(dashboard_file):
    if dashboard_file.exists():
        return json.loads(dashboard_file.read_text())
    return []


def draft_existing_jobs(targets):
    """Draft for jobs already on the dashboard, named by id (or "all").

    This is the on-demand path: nothing here runs during the daily job.
    """
    dashboard_file = DOCS_DIR / "data.json"
    history = load_history(dashboard_file)
    base_cv_text = (DATA_DIR / "base_cv.md").read_text()
    want_all = "all" in targets
    wanted = set(targets)

    todo = [
        job
        for day in history
        for job in day.get("jobs", [])
        if (want_all or job.get("id") in wanted) and not job.get("cover_letter")
    ]
    if not todo:
        print("Nothing to draft - those jobs already have a cover letter, or no id matched")
        return

    print(f"Drafting for {len(todo)} job(s)")
    for job in todo:
        print(f"  {job['title']} @ {job['employer']}")
        try:
            job.update(draft_for_job(job, base_cv_text))
        except Exception as e:                       # noqa: BLE001 - one bad job must not lose the rest
            print(f"    Failed: {e}")

    dashboard_file.write_text(json.dumps(history, indent=2))
    print(f"Updated {dashboard_file}. Run generate_pdfs.py to render the PDFs.")


def collect_new_jobs():
    """Default path: put the day's new jobs on the dashboard, undrafted.

    No API call, so the daily run costs nothing. Each job gets its documents
    written later, only if Maria asks for them.
    """
    new_jobs_file = DATA_DIR / "new_jobs.json"
    if not new_jobs_file.exists():
        print("No new_jobs.json found, nothing to add")
        return

    new_jobs = json.loads(new_jobs_file.read_text())
    drafted = list(new_jobs)
    print(f"Adding {len(drafted)} new job(s) to the dashboard (no drafting)")

    # Load existing dashboard history, merge today's batch into any existing
    # entry for today rather than always inserting a new one - running the
    # workflow more than once on the same day (a scheduled run plus a manual
    # trigger, say) must not split one day's jobs across two dashboard
    # entries with duplicate dates.
    dashboard_file = DOCS_DIR / "data.json"
    history = load_history(dashboard_file)

    today_str = str(date.today())
    existing_today = next((d for d in history if d.get("date") == today_str), None)
    if existing_today is not None:
        seen_ids = {j.get("id") for j in existing_today.get("jobs", [])}
        existing_today["jobs"] = existing_today.get("jobs", []) + [
            j for j in drafted if j.get("id") not in seen_ids
        ]
        history.remove(existing_today)
        history.insert(0, existing_today)
    else:
        history.insert(0, {"date": today_str, "jobs": drafted})
    history = history[:30]  # keep last 30 days

    DOCS_DIR.mkdir(exist_ok=True)
    dashboard_file.write_text(json.dumps(history, indent=2))
    print(f"Wrote {len(drafted)} new jobs to the dashboard")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--draft",
        nargs="+",
        metavar="JOB_ID",
        help=(
            "Draft a cover letter and adapted CV for these job ids (or 'all' "
            "for every undrafted job). Costs API credit; needs "
            "ANTHROPIC_API_KEY. Omit to just add the day's new jobs."
        ),
    )
    args = parser.parse_args()

    if args.draft:
        draft_existing_jobs(args.draft)
    else:
        collect_new_jobs()


if __name__ == "__main__":
    main()
